//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceHumanizerRequest", Namespace="http://schemas.datacontract.org/2004/07/Interviews.VM.PriceHumanizer.ServiceDefin" +
        "ition.Messages")]
    [System.SerializableAttribute()]
    public partial class PriceHumanizerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceHumanizerResponse", Namespace="http://schemas.datacontract.org/2004/07/Interviews.VM.PriceHumanizer.ServiceDefin" +
        "ition.Messages")]
    [System.SerializableAttribute()]
    public partial class PriceHumanizerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string humanizedPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string humanizedPrice {
            get {
                return this.humanizedPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.humanizedPriceField, value) != true)) {
                    this.humanizedPriceField = value;
                    this.RaisePropertyChanged("humanizedPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriceHuminizerHostServiceReference.IPriceHumanizerService")]
    public interface IPriceHumanizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceHumanizerService/HumanizePrice", ReplyAction="http://tempuri.org/IPriceHumanizerService/HumanizePriceResponse")]
        PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse HumanizePrice(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPriceHumanizerService/HumanizePrice", ReplyAction="http://tempuri.org/IPriceHumanizerService/HumanizePriceResponse")]
        System.IAsyncResult BeginHumanizePrice(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request, System.AsyncCallback callback, object asyncState);
        
        PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse EndHumanizePrice(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceHumanizerServiceChannel : PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.IPriceHumanizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanizePriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HumanizePriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceHumanizerServiceClient : System.ServiceModel.ClientBase<PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.IPriceHumanizerService>, PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.IPriceHumanizerService {
        
        private BeginOperationDelegate onBeginHumanizePriceDelegate;
        
        private EndOperationDelegate onEndHumanizePriceDelegate;
        
        private System.Threading.SendOrPostCallback onHumanizePriceCompletedDelegate;
        
        public PriceHumanizerServiceClient() {
        }
        
        public PriceHumanizerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceHumanizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceHumanizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceHumanizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HumanizePriceCompletedEventArgs> HumanizePriceCompleted;
        
        public PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse HumanizePrice(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request) {
            return base.Channel.HumanizePrice(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHumanizePrice(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHumanizePrice(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse EndHumanizePrice(System.IAsyncResult result) {
            return base.Channel.EndHumanizePrice(result);
        }
        
        private System.IAsyncResult OnBeginHumanizePrice(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request = ((PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest)(inValues[0]));
            return this.BeginHumanizePrice(request, callback, asyncState);
        }
        
        private object[] OnEndHumanizePrice(System.IAsyncResult result) {
            PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerResponse retVal = this.EndHumanizePrice(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHumanizePriceCompleted(object state) {
            if ((this.HumanizePriceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HumanizePriceCompleted(this, new HumanizePriceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HumanizePriceAsync(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request) {
            this.HumanizePriceAsync(request, null);
        }
        
        public void HumanizePriceAsync(PriceHumanizerDesktopClient.PriceHuminizerHostServiceReference.PriceHumanizerRequest request, object userState) {
            if ((this.onBeginHumanizePriceDelegate == null)) {
                this.onBeginHumanizePriceDelegate = new BeginOperationDelegate(this.OnBeginHumanizePrice);
            }
            if ((this.onEndHumanizePriceDelegate == null)) {
                this.onEndHumanizePriceDelegate = new EndOperationDelegate(this.OnEndHumanizePrice);
            }
            if ((this.onHumanizePriceCompletedDelegate == null)) {
                this.onHumanizePriceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHumanizePriceCompleted);
            }
            base.InvokeAsync(this.onBeginHumanizePriceDelegate, new object[] {
                        request}, this.onEndHumanizePriceDelegate, this.onHumanizePriceCompletedDelegate, userState);
        }
    }
}
